name = "bd-tour-connect"
compatibility_date = "2024-01-01"
pages_build_output_dir = "build"

[[d1_databases]]
binding = "DB"
database_name = "bd-tour-connect-db"
database_id = "edf51725-8773-47ff-83a8-8b1ecd9f6e7b"
